/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:37:30 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/Montreal.framework/Montreal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray, NSArray;

@interface MLPNDArrayLossLabels : NSObject {

	NSMutableArray* _largeReductionSumResult;
	NSMutableArray* _smallReductionSumResult;
	NSArray* _labels;

}

@property (retain) NSMutableArray * largeReductionSumResult;              //@synthesize largeReductionSumResult=_largeReductionSumResult - In the implementation block
@property (retain) NSMutableArray * smallReductionSumResult;              //@synthesize smallReductionSumResult=_smallReductionSumResult - In the implementation block
@property (retain) NSArray * labels;                                      //@synthesize labels=_labels - In the implementation block
-(id)init;
-(NSMutableArray *)largeReductionSumResult;
-(NSMutableArray *)smallReductionSumResult;
-(NSArray *)labels;
-(void)setLabels:(NSArray *)arg1 ;
-(void)setLargeReductionSumResult:(NSMutableArray *)arg1 ;
-(void)setSmallReductionSumResult:(NSMutableArray *)arg1 ;
@end

