/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:43:59 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/SafariServices.framework/SafariServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol _SFAppleConnectExtensionUIDelegate <NSObject>
@required
-(void)appleConnectExtensionPageController:(id)arg1 presentViewController:(id)arg2;
-(void)appleConnectExtensionPageController:(id)arg1 dismissViewController:(id)arg2;

@end

