/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:52:30 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/CDDataAccess.framework/CDDataAccess
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface DAContactsAccountProvider : NSObject
+(id)providerWithContactStore:(id)arg1 ;
+(id)providerWithAddressBook:(void*)arg1 ;
-(id)allAccounts;
-(id)fetchedAccountWithExternalIdentifier:(id)arg1 ;
-(id)accountByCreatingAccountWithExternalIdentifier:(id)arg1 ;
-(id)accountForContainerWithIdentifier:(id)arg1 ;
@end

