/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:52:58 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class HDProfile, NSObject, _DPStringRecorder;

@interface HDDiffPrivReporter : NSObject {

	HDProfile* _profile;
	NSObject*<OS_dispatch_queue> _queue;
	_DPStringRecorder* _recorder;

}
+(BOOL)isAvailable;
+(id)reportableTypes;
-(id)initWithProfile:(id)arg1 ;
-(id)_typesInMonthWithDataForTypes:(id)arg1 now:(id)arg2 error:(id*)arg3 ;
-(BOOL)_recordTypesUsedInPastMonth:(id)arg1 ;
-(BOOL)reportWithCurrentDate:(id)arg1 error:(id*)arg2 ;
@end

