/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:47:12 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMapTable;

@interface BBGuaranteedOnceCache : NSObject {

	NSMapTable* _guaranteedCache;
	NSMapTable* _bestEffortCache;

}
-(id)init;
-(void)removeObjectUsingKey:(id)arg1 ;
-(BOOL)attemptToGuaranteeObjectUsingKey:(id)arg1 ;
-(id)objectUsingKeyRemovingGuarantee:(id)arg1 ;
-(void)cacheObject:(id)arg1 usingKey:(id)arg2 ;
@end

