/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:41:28 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class MPModelSocialPerson;


@protocol MPStoreSocialRequestOperationDataSource <NSObject>
@property (nonatomic,retain) MPModelSocialPerson * person; 
@optional
-(id)fallbackBagKeys;
-(id)fallbackURLString;

@required
-(id)queryItems;
-(id)bagKey;
-(MPModelSocialPerson *)person;
-(void)setPerson:(id)arg1;
-(id)httpBody;
-(long long)httpBodyType;
-(long long)httpMethod;

@end

