/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:48:55 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/SXComponent.h>

@class NSString, NSAttributedString;

@interface SXImageComponent : SXComponent

@property (nonatomic,readonly) NSString * imageIdentifier; 
@property (nonatomic,readonly) NSString * caption; 
@property (nonatomic,readonly) BOOL userControllable; 
@property (nonatomic,readonly) BOOL shouldBeExposedToAssistiveTechnology; 
@property (nonatomic,readonly) NSAttributedString * captionWithLocalizedRoleForSpeaking; 
+(id)typeString;
-(BOOL)userControllable;
-(NSString *)caption;
-(NSString *)imageIdentifier;
-(unsigned long long)traits;
-(NSAttributedString *)captionWithLocalizedRoleForSpeaking;
-(BOOL)shouldBeExposedToAssistiveTechnology;
@end

