/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:43:21 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/MapKit.framework/MapKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableSet, NSString;

@interface _MXExtensionContainingAppProxy : NSObject {

	NSMutableSet* _extensionUIIdentifiers;
	NSMutableSet* _extensionNonUIIdentifiers;
	NSString* _containingAppIdentifer;

}

@property (nonatomic,copy,readonly) NSString * containingAppIdentifer;              //@synthesize containingAppIdentifer=_containingAppIdentifer - In the implementation block
@property (nonatomic,retain) NSMutableSet * extensionNonUIIdentifiers;              //@synthesize extensionNonUIIdentifiers=_extensionNonUIIdentifiers - In the implementation block
@property (nonatomic,retain) NSMutableSet * extensionUIIdentifiers;                 //@synthesize extensionUIIdentifiers=_extensionUIIdentifiers - In the implementation block
-(id)initWithContainingAppIdentifer:(id)arg1 ;
-(NSMutableSet *)extensionUIIdentifiers;
-(void)setExtensionUIIdentifiers:(NSMutableSet *)arg1 ;
-(NSMutableSet *)extensionNonUIIdentifiers;
-(void)setExtensionNonUIIdentifiers:(NSMutableSet *)arg1 ;
-(NSString *)containingAppIdentifer;
@end

