/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:43:23 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/MapKit.framework/MapKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NSFastEnumeration
@required
-(unsigned long long)countByEnumeratingWithState:(SCD_Struct_MK33*)arg1 objects:(id*)arg2 count:(unsigned long long)arg3;

@end

