/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:50:25 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/ClockKit.framework/ClockKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CLKComplicationServer <NSObject>
@required
-(void)checkinWithClientIdentifier:(id)arg1 bundlePath:(id)arg2;
-(void)reloadTimelineForComplication:(id)arg1;
-(void)extendTimelineForComplication:(id)arg1;

@end

