/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:52:12 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/MediaControls.framework/MediaControls
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, UIColor;

@interface MediaControlsExpandableButtonOption : NSObject {

	NSString* _identifier;
	NSString* _packageName;
	NSString* _title;
	UIColor* _selectedBackgroundColor;

}

@property (nonatomic,retain) NSString * identifier;                          //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic,retain) NSString * packageName;                         //@synthesize packageName=_packageName - In the implementation block
@property (nonatomic,retain) NSString * title;                               //@synthesize title=_title - In the implementation block
@property (nonatomic,retain) UIColor * selectedBackgroundColor;              //@synthesize selectedBackgroundColor=_selectedBackgroundColor - In the implementation block
-(NSString *)identifier;
-(void)setIdentifier:(NSString *)arg1 ;
-(NSString *)title;
-(void)setTitle:(NSString *)arg1 ;
-(NSString *)packageName;
-(void)setPackageName:(NSString *)arg1 ;
-(void)setSelectedBackgroundColor:(UIColor *)arg1 ;
-(UIColor *)selectedBackgroundColor;
@end

