/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:46:04 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/FileProvider.framework/FileProvider
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <FileProvider/FPActionOperation.h>

@class NSProgress, FPProviderDomain;

@interface FPDisconnectDomainOperation : FPActionOperation {

	NSProgress* _remoteProgress;
	FPProviderDomain* _domain;

}
-(void)cancel;
-(id)initWithDomain:(id)arg1 ;
-(void)actionMain;
-(void)_tryDisconnectingSafely:(BOOL)arg1 ;
@end

