/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:45:23 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/SpringBoardFoundation.framework/SpringBoardFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoardFoundation/SBAbstractSpringBoardDefaultDomain.h>

@interface SBSOSDefaults : SBAbstractSpringBoardDefaultDomain

@property (nonatomic,readonly) BOOL disablesForAccessibility; 
@property (assign,nonatomic) BOOL performedCheckForTripleClickSOSMigrationAlert; 
-(void)setPerformedCheckForTripleClickSOSMigrationAlert:(BOOL)arg1 ;
-(BOOL)performedCheckForTripleClickSOSMigrationAlert;
-(void)setDisablesForAccessibility:(BOOL)arg1 ;
-(BOOL)disablesForAccessibility;
-(void)_bindAndRegisterDefaults;
-(BOOL)isAutomaticCallCountdownEnabled;
-(long long)lockButtonSOSTriggerCount;
-(BOOL)clawCanTriggerSOS;
@end

