/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:48:10 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/ContactsDonation.framework/ContactsDonation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol DonationAgentProtocol;
@class CNPromise;

@interface _CNDonationAgentXPCMethodScope : NSObject {

	id<DonationAgentProtocol> _proxy;
	CNPromise* _promise;

}

@property (nonatomic,readonly) id<DonationAgentProtocol> proxy;              //@synthesize proxy=_proxy - In the implementation block
@property (nonatomic,readonly) CNPromise * promise;                          //@synthesize promise=_promise - In the implementation block
-(id)init;
-(id<DonationAgentProtocol>)proxy;
-(CNPromise *)promise;
-(id)initWithConnection:(id)arg1 promise:(id)arg2 proxy:(id)arg3 ;
-(id)initWithPromise:(id)arg1 proxy:(id)arg2 ;
@end

