/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:48:28 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/ProtectedCloudStorage.framework/ProtectedCloudStorage
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct _NSZone* NSZoneRef;

typedef struct _PCSIdentityData* PCSIdentityDataRef;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct _PCSPublicIdentityData* PCSPublicIdentityDataRef;

typedef struct _PCSIdentitySetData* PCSIdentitySetDataRef;

typedef struct __PCSLogContext* PCSLogContextRef;

typedef struct __CFData* CFDataRef;

typedef struct __CFError* CFErrorRef;

typedef struct sqlite3* sqlite3Ref;

typedef struct sqlite3_stmt* sqlite3_stmtRef;

