/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:56:30 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface EDPivotPageField : NSObject {

	unsigned long long mFieldId;
	NSString* mCap;
	NSString* mName;

}
+(id)pivotPageField;
-(id)init;
-(id)description;
-(id)name;
-(void)setName:(id)arg1 ;
-(unsigned long long)fieldId;
-(void)setFieldId:(unsigned long long)arg1 ;
-(id)cap;
-(void)setCap:(id)arg1 ;
@end

