/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:50:41 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <HMFoundation/HMFMessageFilter.h>

@interface HMDRemoteMessageFilter : HMFMessageFilter
+(BOOL)canInitWithMessage:(id)arg1 ;
+(id)policyClasses;
-(BOOL)acceptWithPolicies:(id)arg1 error:(id*)arg2 ;
@end

