/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:53:57 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WorkflowUI/WorkflowUI-Structs.h>
#import <ComponentKit/CKCompositeComponent.h>

@interface WFRowTemplateItemLabelComponent : CKCompositeComponent
+(id)newWithString:(id)arg1 options:(const WFRowTemplateItemLabelComponentOptions*)arg2 size:(const CKComponentSize*)arg3 ;
@end

