/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:51:42 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/PersonalizationPortraitInternals
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol PPNamedEntityReadOnlyServerProtocol <PPFeedbackAccepting>
@required
-(void)mapItemForPlaceName:(id)arg1 completion:(/*^block*/id)arg2;
-(void)namedEntityRecordsWithQuery:(id)arg1 queryId:(unsigned long long)arg2;
-(void)rankedNamedEntitiesWithQuery:(id)arg1 queryId:(unsigned long long)arg2;

@end

