/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:43:04 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface CLDeviceMotionProperties : NSObject {

	int _mode;

}

@property (assign,nonatomic) int mode;              //@synthesize mode=_mode - In the implementation block
-(id)description;
-(void)setMode:(int)arg1 ;
-(int)mode;
-(id)initWithMode:(int)arg1 ;
@end

