/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:43:04 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <CoreMotion/CoreMotion-Structs.h>
@interface CMAmbientPressureDataInternal : NSObject {

	SCD_Struct_CM323 fPressure;

}
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setAmbientPressure:(SCD_Struct_CM323)arg1 ;
-(id)initWithPressure:(SCD_Struct_CM323)arg1 ;
@end

