/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:49:04 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/Tips.framework/Tips
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Tips/TPSAnalyticsEvent.h>

@class NSNumber;

@interface TPSAnalyticsEventAppLeavesScreen : TPSAnalyticsEvent {

	NSNumber* _previouslyUnseenTipViews;
	NSNumber* _collectionViews;
	NSNumber* _tipViewsThisSession;

}

@property (nonatomic,readonly) NSNumber * previouslyUnseenTipViewsInThisSession; 
@property (nonatomic,readonly) NSNumber * collectionViews; 
@property (nonatomic,readonly) NSNumber * tipViewsInThisSession; 
+(BOOL)supportsSecureCoding;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)eventName;
-(NSNumber *)collectionViews;
-(id)analyticsEventRepresentation;
-(NSNumber *)tipViewsInThisSession;
-(NSNumber *)previouslyUnseenTipViewsInThisSession;
@end

