/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:49:04 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/Tips.framework/Tips
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Tips/TPSAnalyticsEvent.h>

@class NSNumber;

@interface TPSAnalyticsEventAppDeleted : TPSAnalyticsEvent {

	NSNumber* _contentViewTotal;

}

@property (nonatomic,readonly) double timeSinceLastNotification; 
@property (nonatomic,readonly) NSNumber * notificationsPosted; 
@property (nonatomic,readonly) NSNumber * appLaunches; 
@property (nonatomic,readonly) NSNumber * contentViewTotal;                   //@synthesize contentViewTotal=_contentViewTotal - In the implementation block
@property (nonatomic,readonly) NSNumber * desiredOutcomeTotal; 
+(BOOL)supportsSecureCoding;
-(id)eventName;
-(id)analyticsEventRepresentation;
-(NSNumber *)notificationsPosted;
-(NSNumber *)appLaunches;
-(NSNumber *)contentViewTotal;
-(NSNumber *)desiredOutcomeTotal;
-(double)timeSinceLastNotification;
-(id)tipViewTotal;
@end

