/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:54:17 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/CarPlay.framework/CarPlay
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSArray, CPBarButton;


@protocol CPBarButtonProviding <NSObject>
@property (nonatomic,retain) NSArray * leadingNavigationBarButtons; 
@property (nonatomic,retain) NSArray * trailingNavigationBarButtons; 
@property (nonatomic,retain) CPBarButton * backButton; 
@required
-(CPBarButton *)backButton;
-(void)setBackButton:(id)arg1;
-(NSArray *)leadingNavigationBarButtons;
-(void)setLeadingNavigationBarButtons:(id)arg1;
-(NSArray *)trailingNavigationBarButtons;
-(void)setTrailingNavigationBarButtons:(id)arg1;

@end

