/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:38:58 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/Vision.framework/Vision
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Vision/VNCompoundRequest.h>

@class NSMapTable;

@interface VNHomologousObservationClassCompoundRequest : VNCompoundRequest {

	NSMapTable* _requestsClassMapping;

}
-(void)assignOriginalRequestsResultsFromObservations:(id)arg1 obtainedInPerformingContext:(id)arg2 ;
-(id)initWithSubrequests:(id)arg1 ;
-(id)originalRequestsOfClass:(Class)arg1 ;
@end

