/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:48:50 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/NewsUI.framework/NewsUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NUSizer;
@class NSArray;

@interface NULayoutContextSizer : NSObject {

	id<NUSizer> _sizer;
	NSArray* _attributes;

}

@property (nonatomic,retain) id<NUSizer> sizer;                   //@synthesize sizer=_sizer - In the implementation block
@property (nonatomic,readonly) NSArray * attributes;              //@synthesize attributes=_attributes - In the implementation block
-(id)description;
-(NSArray *)attributes;
-(BOOL)matchForLayoutContext:(id)arg1 ;
-(id<NUSizer>)sizer;
-(id)initWithSizer:(id)arg1 attributes:(id)arg2 ;
-(void)setSizer:(id<NUSizer>)arg1 ;
@end

