/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:48:49 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/NewsUI.framework/NewsUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsUI/NewsUI-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface NUVideoViewControllerAdConfiguration : NSObject <NSCopying> {

	BOOL _adsEnabled;
	BOOL _allowLeadingAdSlot;

}

@property (getter=areAdsEnabled,nonatomic,readonly) BOOL adsEnabled;              //@synthesize adsEnabled=_adsEnabled - In the implementation block
@property (nonatomic,readonly) BOOL allowLeadingAdSlot;                           //@synthesize allowLeadingAdSlot=_allowLeadingAdSlot - In the implementation block
-(id)init;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)initWithAdsEnabled:(BOOL)arg1 allowLeadingAdSlot:(BOOL)arg2 ;
-(BOOL)areAdsEnabled;
-(BOOL)allowLeadingAdSlot;
@end

