/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 8, 2020 at 8:06:07 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/AccessibilityBundles/CameraUI.axbundle/CameraUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CameraUI/CameraUI-Structs.h>
#import <CameraUI/__CAMPanoramaViewAccessibility_super.h>

@interface CAMPanoramaViewAccessibility : __CAMPanoramaViewAccessibility_super
+(id)safeCategoryTargetClassName;
+(void)_accessibilityPerformValidations:(id)arg1 ;
+(Class)safeCategoryBaseClass;
-(id)_accessibilityHitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
@end

