/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:56:56 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/RemoteServiceDiscovery.framework/RemoteServiceDiscovery
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_xpc_object;
@class NSObject, OS_remote_device;

@interface OS_remote_service : NSObject {

	char* name;
	NSObject*<OS_xpc_object> properties;
	NSObject*<OS_xpc_object> connection;
	OS_remote_device* device;
	unsigned connect_timeout;

}
-(void)dealloc;
@end

