/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:57:30 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/TrialServer.framework/TrialServer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TrialServer/TRIExperimentBaseTask.h>

@interface TRIFetchExperimentTask : TRIExperimentBaseTask
+(id)taskWithExperimentId:(id)arg1 ;
-(id)description;
-(int)runTask;
-(BOOL)saveExperiment:(id)arg1 ;
@end

