/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 8, 2020 at 8:04:20 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PreferenceBundles/MobileSafariSettings.bundle/MobileSafariSettings
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SafariShared/WBSFrequentlyVisitedSitesController.h>

@class NSMutableArray, WebBookmarkCollection;

@interface FrequentlyVisitedSitesController : WBSFrequentlyVisitedSitesController {

	NSMutableArray* _cachedFrequentlyVisitedBookmarks;
	WebBookmarkCollection* _bookmarkCollection;
	BOOL _bookmarksNeedToSave;
	BOOL _ignoreBookmarksFolderChangeNotifications;

}
+(id)sharedController;
-(void)dealloc;
-(id)_canonicalizedFavoritesURLStringSet;
-(id)frequentlyVisitedSites;
-(void)clearFrequentlyVisitedSites;
-(id)initWithBookmarkCollection:(id)arg1 ;
-(void)_receivedBookmarksFolderContentChangedNotification:(id)arg1 ;
-(void)_clearFrequentlyVisitedSitesInBookmarksDB;
-(void)promoteFrequentlyVisitedSite:(id)arg1 toFavoriteAtIndex:(unsigned long long)arg2 ;
-(void)banFrequentlyVisitedSite:(id)arg1 inMemoryBookmarkChangeTrackingAvailable:(BOOL)arg2 ;
-(void)saveFrequentlyVisitedSitesToBookmarksDBWithCompletion:(/*^block*/id)arg1 ;
@end

