/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:45:55 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/TelephonyUI.framework/TelephonyUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TelephonyUI/TPBottomSingleButtonBar.h>

@class TPButton;

@interface TPBottomDoubleButtonBar : TPBottomSingleButtonBar {

	TPButton* _button2;

}
-(void)layoutSubviews;
-(double)_buttonWidth;
-(void)_layoutButtons;
-(void)setButton:(id)arg1 andStyle:(BOOL)arg2 ;
-(void)setButton2:(id)arg1 andStyle:(BOOL)arg2 ;
-(id)button2;
@end

