/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:48:34 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/AvatarUI.framework/AvatarUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AvatarUI/AvatarUI-Structs.h>
#import <AvatarUI/AVTImageStore.h>

@interface AVTClippableImageStore : AVTImageStore
-(BOOL)saveImage:(id)arg1 forItem:(id)arg2 scope:(id)arg3 clippingRect:(CGRect)arg4 error:(id*)arg5 ;
-(CGRect)resourceClippingRectForItem:(id)arg1 scope:(id)arg2 ;
@end

