/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:48:30 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/ARKit.framework/ARKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface ARConfigurationGraphUtility : NSObject
+(id)_tableNodeFromList:(id)arg1 name:(id)arg2 title:(id)arg3 ;
+(id)dotGraphFromConfiguration:(id)arg1 ;
@end

