/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:48:33 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/ARKit.framework/ARKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <ARKit/ARKit-Structs.h>
@interface ARMLImageDownScalingResult : NSObject {

	CVBufferRef _pixelBuffer;
	CVBufferRef _undistortedPixelBuffer;
	CGSize _regionOfInterest;
	CGRect _cropRegion;

}

@property (nonatomic,readonly) CVBufferRef pixelBuffer;                       //@synthesize pixelBuffer=_pixelBuffer - In the implementation block
@property (nonatomic,readonly) CGSize imageResolution; 
@property (nonatomic,readonly) CGSize regionOfInterest;                       //@synthesize regionOfInterest=_regionOfInterest - In the implementation block
@property (nonatomic,readonly) CGRect cropRegion;                             //@synthesize cropRegion=_cropRegion - In the implementation block
@property (assign,nonatomic) CVBufferRef undistortedPixelBuffer;              //@synthesize undistortedPixelBuffer=_undistortedPixelBuffer - In the implementation block
-(void)dealloc;
-(CVBufferRef)pixelBuffer;
-(CGSize)regionOfInterest;
-(void)setPixelBuffer:(CVBufferRef)arg1 ;
-(CGSize)imageResolution;
-(id)initWithPixelBuffer:(CVBufferRef)arg1 regionOfInterest:(CGSize)arg2 cropRegion:(CGRect)arg3 ;
-(CVBufferRef)undistortedPixelBuffer;
-(void)setUndistortedPixelBuffer:(CVBufferRef)arg1 ;
-(CGRect)cropRegion;
@end

