/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:49:45 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/TSReading.framework/TSReading
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class TSSMutablePropertySet;

@interface TSSPropertySetChangeDetails : NSObject {

	TSSMutablePropertySet* mChangedProperties;

}
-(id)init;
-(void)dealloc;
-(id)changedProperties;
-(id)initWithChangedProperties:(id)arg1 ;
-(void)addChangedProperty:(int)arg1 ;
-(void)addChangedProperties:(id)arg1 ;
@end

