/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:55:17 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/DASDaemon.framework/DASDaemon
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate, NSObject;

@interface _DASLogValueInterval : NSObject {

	NSDate* _startDate;
	NSDate* _endDate;
	NSObject* _value;

}

@property (nonatomic,retain) NSDate * startDate;              //@synthesize startDate=_startDate - In the implementation block
@property (nonatomic,retain) NSDate * endDate;                //@synthesize endDate=_endDate - In the implementation block
@property (nonatomic,retain) NSObject * value;                //@synthesize value=_value - In the implementation block
-(BOOL)isEqual:(id)arg1 ;
-(id)description;
-(NSObject *)value;
-(void)setValue:(NSObject *)arg1 ;
-(NSDate *)startDate;
-(NSDate *)endDate;
-(double)duration;
-(void)setStartDate:(NSDate *)arg1 ;
-(void)setEndDate:(NSDate *)arg1 ;
-(id)durationString;
-(id)intervalString;
@end

