/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:55:04 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/CarPlaySupport.framework/CarPlaySupport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSArray;


@protocol CPListDataSource <NSObject>
@property (nonatomic,readonly) long long numberOfSections; 
@property (nonatomic,readonly) NSArray * items; 
@required
-(NSArray *)items;
-(long long)numberOfSections;
-(long long)numberOfItemsInSection:(long long)arg1;
-(id)itemAtIndexPath:(id)arg1;

@end

