/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:56:56 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/RemoteManagement.framework/RemoteManagement
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray, NSString;

@interface RMStatusPublisherDescription : NSObject {

	NSArray* _keyPaths;
	NSString* _principalClassName;

}

@property (nonatomic,copy,readonly) NSArray * keyPaths;                         //@synthesize keyPaths=_keyPaths - In the implementation block
@property (nonatomic,copy,readonly) NSString * principalClassName;              //@synthesize principalClassName=_principalClassName - In the implementation block
-(id)initWithDictionary:(id)arg1 ;
-(NSArray *)keyPaths;
-(id)initWithKeyPaths:(id)arg1 principalClassName:(id)arg2 ;
-(NSString *)principalClassName;
@end

