/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:55:30 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/FamilyCircleUI.framework/FamilyCircleUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol AAUIContactsSearchDelegate <NSObject>
@required
-(void)contactsSearchController:(id)arg1 didFinishSearchWithSuccess:(BOOL)arg2;
-(void)contactsSearchController:(id)arg1 didFindSortedResult:(id)arg2;

@end

