/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:54:43 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WorkflowKit/WFHandleSystemIntentAction.h>

@class WFImage;

@interface WFHandlePaymentIntentAction : WFHandleSystemIntentAction {

	WFImage* _icon;

}
-(id)icon;
-(BOOL)showsWhenRun;
-(BOOL)opensInApp;
-(id)errorFromResolutionResult:(id)arg1 forSlot:(id)arg2 onIntent:(id)arg3 ;
-(id)errorFromConfirmResponse:(id)arg1 intent:(id)arg2 ;
-(id)errorFromHandleResponse:(id)arg1 intent:(id)arg2 ;
-(id)localizedKeyParameterDisplayName;
-(id)localizedPaymentServiceName;
-(id)noRecipientAccountError:(BOOL)arg1 ;
-(id)credentialsUnverifiedError;
-(id)amountBelowMinimumErrorWithAmount:(id)arg1 sending:(BOOL)arg2 ;
-(id)amountAboveMaximumErrorWithAmount:(id)arg1 sending:(BOOL)arg2 ;
-(id)currencyUnsupportedErrorWithAmount:(id)arg1 ;
-(id)noBankAccountError;
-(id)insufficientFundsError;
-(id)errorFromPaymentsResponse:(id)arg1 intent:(id)arg2 ;
@end

