/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 8, 2020 at 8:06:06 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/AccessibilityBundles/MessageUIFramework.axbundle/MessageUIFramework
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessageUIFramework/__WebAccessibilityObjectWrapperAccessibility__MessageUI__WebCore_super.h>

@interface WebAccessibilityObjectWrapperAccessibility__MessageUI__WebCore : __WebAccessibilityObjectWrapperAccessibility__MessageUI__WebCore_super
+(id)safeCategoryTargetClassName;
+(void)_accessibilityPerformValidations:(id)arg1 ;
+(Class)safeCategoryBaseClass;
-(id)accessibilityLabel;
-(id)accessibilityValue;
-(id)accessibilityHint;
-(BOOL)_axIsAttachmentType;
@end

