/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:57:47 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/WelcomeKitCore.framework/WelcomeKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <WelcomeKitCore/WelcomeKitCore-Structs.h>
@class NSString;

@interface WLWiFiNetwork : NSObject {

	WiFiNetworkRef _ref;

}

@property (assign,nonatomic) WiFiNetworkRef ref;              //@synthesize ref=_ref - In the implementation block
@property (nonatomic,readonly) NSString * ssid; 
-(void)dealloc;
-(NSString *)ssid;
-(WiFiNetworkRef)ref;
-(void)setRef:(WiFiNetworkRef)arg1 ;
-(id)initWithWiFiNetworkRef:(WiFiNetworkRef)arg1 ;
@end

