/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:48:14 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/CoreHaptics.framework/CoreHaptics
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface CHHapticDynamicParameter : NSObject {

	NSString* _param;
	float _value;
	double _time;

}

@property (readonly) NSString * parameterID;              //@synthesize param=_param - In the implementation block
@property (assign) float value;                           //@synthesize value=_value - In the implementation block
@property (assign) double relativeTime;                   //@synthesize time=_time - In the implementation block
-(id)init;
-(float)value;
-(void)setValue:(float)arg1 ;
-(id)initWithParameterID:(id)arg1 value:(float)arg2 relativeTime:(double)arg3 ;
-(void)setRelativeTime:(double)arg1 ;
-(double)relativeTime;
-(NSString *)parameterID;
@end

