/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:57:46 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/WebInspector.framework/WebInspector
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WebInspector/RWIProtocolJSONObject.h>

@interface RWIProtocolDOMRGBAColor : RWIProtocolJSONObject

@property (assign,nonatomic) int r; 
@property (assign,nonatomic) int g; 
@property (assign,nonatomic) int b; 
@property (assign,nonatomic) double a; 
+(id)safe_initWithR:(int)arg1 g:(int)arg2 b:(int)arg3 ;
-(id)ik_color;
-(int)g;
-(void)setG:(int)arg1 ;
-(int)r;
-(int)b;
-(double)a;
-(void)setA:(double)arg1 ;
-(void)setB:(int)arg1 ;
-(void)setR:(int)arg1 ;
-(id)initWithR:(int)arg1 g:(int)arg2 b:(int)arg3 ;
@end

