/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:48:43 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/Widgets.framework/Widgets
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Widgets/Widgets-Structs.h>
#import <UIKitCore/UIView.h>

@class UIView, WGWidgetPlatterView;

@interface WGWidgetWrapperView : UIView {

	UIView* _contentView;
	WGWidgetPlatterView* _platterView;
	double _overrideIntrinsicContentHeight;
	double _topMarginForLayout;

}

@property (nonatomic,readonly) UIView * contentView;                             //@synthesize contentView=_contentView - In the implementation block
@property (nonatomic,retain) WGWidgetPlatterView * platterView;                  //@synthesize platterView=_platterView - In the implementation block
@property (assign,nonatomic) double overrideIntrinsicContentHeight;              //@synthesize overrideIntrinsicContentHeight=_overrideIntrinsicContentHeight - In the implementation block
@property (assign,nonatomic) double topMarginForLayout;                          //@synthesize topMarginForLayout=_topMarginForLayout - In the implementation block
-(UIView *)contentView;
-(CGSize)intrinsicContentSize;
-(void)layoutSubviews;
-(void)setPlatterView:(WGWidgetPlatterView *)arg1 ;
-(WGWidgetPlatterView *)platterView;
-(void)setTopMarginForLayout:(double)arg1 ;
-(id)initWithPlatterView:(id)arg1 ;
-(void)setOverrideIntrinsicContentHeight:(double)arg1 ;
-(double)overrideIntrinsicContentHeight;
-(double)topMarginForLayout;
@end

