/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:48:39 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoardHome/SBHScaleZoomSettings.h>

@class SBFAnimationSettings;

@interface SBHCrossfadeZoomSettings : SBHScaleZoomSettings {

	BOOL _morphWithZoom;
	SBFAnimationSettings* _morphSettings;

}

@property (assign,nonatomic) BOOL morphWithZoom;                                //@synthesize morphWithZoom=_morphWithZoom - In the implementation block
@property (nonatomic,retain) SBFAnimationSettings * morphSettings;              //@synthesize morphSettings=_morphSettings - In the implementation block
+(id)settingsControllerModule;
-(void)setDefaultValues;
-(id)effectiveMorphAnimationSettings;
-(void)setMorphWithZoom:(BOOL)arg1 ;
-(BOOL)morphWithZoom;
-(SBFAnimationSettings *)morphSettings;
-(void)setMorphSettings:(SBFAnimationSettings *)arg1 ;
@end

