/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:56:57 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/SAML.framework/SAML
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SAML/SAMLBaseElement.h>

@class NSString;

@interface SAMLStatusCode : SAMLBaseElement

@property (nonatomic,readonly) NSString * value; 
@property (nonatomic,readonly) SAMLStatusCode * statusCode; 
+(id)createElement:(id*)arg1 ;
-(NSString *)value;
-(SAMLStatusCode *)statusCode;
@end

