/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:49:32 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/AppPredictionUI.framework/AppPredictionUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol APUILongLookViewControllerDataSource
@required
-(id)interfaceActionsForLongLook:(id)arg1;
-(id)appIconImageForLongLook:(id)arg1;
-(id)bundleIdentifierForAppIconInLongLook:(id)arg1;
-(id)titleForLongLookHeaderInLongLook:(id)arg1;
-(BOOL)fetchViewControllerForContentViewInLongLook:(id)arg1 completion:(/*^block*/id)arg2;
-(double)preferredContentHeightForLongLook:(id)arg1;

@end

