/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:46:21 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SAObjects/SABaseClientBoundCommand.h>

@interface SADeviceConfiguration : SABaseClientBoundCommand

@property (assign,nonatomic) double initialInterstitialDelay; 
@property (assign,nonatomic) double initialInterstitialDelayForCarPlay; 
@property (assign,nonatomic) double initialInterstitialDelayForVoiceTriggerOneShotWithoutAudioDucking; 
+(id)deviceConfiguration;
+(id)deviceConfigurationWithDictionary:(id)arg1 context:(id)arg2 ;
-(id)groupIdentifier;
-(id)encodedClassName;
-(BOOL)requiresResponse;
-(double)initialInterstitialDelay;
-(void)setInitialInterstitialDelay:(double)arg1 ;
-(double)initialInterstitialDelayForCarPlay;
-(void)setInitialInterstitialDelayForCarPlay:(double)arg1 ;
-(double)initialInterstitialDelayForVoiceTriggerOneShotWithoutAudioDucking;
-(void)setInitialInterstitialDelayForVoiceTriggerOneShotWithoutAudioDucking:(double)arg1 ;
@end

