/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:49:09 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/CloudKitDaemon.framework/CloudKitDaemon
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CloudKit/CKOperationInfo.h>

@class NSString;

@interface CKFetchTranscodeServerPublicKeyOperationInfo : CKOperationInfo {

	NSString* _transcodeServerHostname;

}

@property (nonatomic,retain) NSString * transcodeServerHostname;              //@synthesize transcodeServerHostname=_transcodeServerHostname - In the implementation block
-(NSString *)transcodeServerHostname;
-(void)setTranscodeServerHostname:(NSString *)arg1 ;
@end

