/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:52:31 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/DoNotDisturbServer.framework/DoNotDisturbServer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary;

@interface DNDSClientDetailsProvider : NSObject {

	NSMutableDictionary* _detailsByIdentifier;

}
+(id)_defaultModuleDirectories;
-(id)init;
-(id)clientDetailsForIdentifier:(id)arg1 ;
-(void)_loadPreloadBundles;
-(id)clientDetailsForIdentifier:(id)arg1 applicationBundleURL:(id)arg2 ;
-(id)findClientDetailsForIdentifier:(id)arg1 ;
@end

