/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 8, 2020 at 8:06:01 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /usr/lib/libtzupdate.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface TZUtilities : NSObject
+(id)stringWithContentsOfFileAtURL:(id)arg1 error:(id*)arg2 ;
+(BOOL)fileExistsAndIsSymbolicLinkAtURL:(id)arg1 ;
@end

