/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:48:36 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/AvatarUI.framework/AvatarUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary;

@interface AVTAvatarAttributeEditorState : NSObject {

	NSMutableDictionary* _pairedStates;

}

@property (nonatomic,retain) NSMutableDictionary * pairedStates;              //@synthesize pairedStates=_pairedStates - In the implementation block
+(id)buildStateFromCoreModel:(id)arg1 avatarConfiguration:(id)arg2 ;
-(id)init;
-(BOOL)isCategoryPaired:(long long)arg1 ;
-(void)setCategory:(long long)arg1 inPairedState:(BOOL)arg2 ;
-(id)initWithPairedStates:(id)arg1 ;
-(NSMutableDictionary *)pairedStates;
-(void)setPairedStates:(NSMutableDictionary *)arg1 ;
@end

