/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:47:14 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/SafariCore.framework/SafariCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SafariCore/SafariCore-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface WBSAnalyticsSafariEnterPasswordsPreferencesEvent : PBCodable <NSCopying> {

	unsigned long long _percentageOfDuplicatedPasswords;
	unsigned long long _timestamp;
	SCD_Struct_WB1 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                                    //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasPercentageOfDuplicatedPasswords; 
@property (assign,nonatomic) unsigned long long percentageOfDuplicatedPasswords;              //@synthesize percentageOfDuplicatedPasswords=_percentageOfDuplicatedPasswords - In the implementation block
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(unsigned long long)timestamp;
-(BOOL)hasTimestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(void)setPercentageOfDuplicatedPasswords:(unsigned long long)arg1 ;
-(void)setHasPercentageOfDuplicatedPasswords:(BOOL)arg1 ;
-(BOOL)hasPercentageOfDuplicatedPasswords;
-(unsigned long long)percentageOfDuplicatedPasswords;
@end

