/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:53:30 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/InputContext.framework/InputContext
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface _ICPortraitUtilities : NSObject
+(id)contactRecordFromPortraitContactRecord:(id)arg1 ;
+(id)namedEntityRecordFromPortraitNamedEntity:(id)arg1 ;
+(unsigned char)namedEntityChangeTypeForPortraitNamedEntityChangeType:(unsigned char)arg1 ;
+(id)contactFromPortraitContact:(id)arg1 ;
+(unsigned char)contactChangeTypeForPortraitChangeType:(unsigned char)arg1 ;
@end

