/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:54:51 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/AppleNeuralEngine.framework/AppleNeuralEngine
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface _ANEErrors : NSObject
+(id)programInferenceOverflowErrorForMethod:(id)arg1 ;
+(id)programInferenceOtherErrorForMethod:(id)arg1 ;
+(id)entitlementErrorForMethod:(id)arg1 ;
+(id)priorityErrorForMethod:(id)arg1 ;
+(id)timeoutErrorForMethod:(id)arg1 ;
+(id)createErrorWithCode:(long long)arg1 description:(id)arg2 ;
+(id)programCreationErrorForMethod:(id)arg1 ;
+(id)programLoadErrorForMethod:(id)arg1 ;
+(id)missingCodeSigningErrorForMethod:(id)arg1 ;
@end

