/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:52:29 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/VoiceShortcuts.framework/VoiceShortcuts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <VoiceShortcuts/VCIntentDefinitionSyncDataHandler.h>
#import <libobjc.A.dylib/INVCIntentDefinitionManager.h>

@class NSString;

@interface VCIntentDefinitionManager : VCIntentDefinitionSyncDataHandler <INVCIntentDefinitionManager>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)intentDefinitionURLsForBundleID:(id)arg1 ;
+(id)intentDefinitionLocalizableFileURLsForBundleID:(id)arg1 ;
+(id)appInfoForBundleID:(id)arg1 ;
+(id)intentDefinitionURLsForBundleID:(id)arg1 withExtensions:(id)arg2 ;
@end

