/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:46:17 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/MobileTimer.framework/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MTBedtimeDNDStateMachineEventHandler <MTStateMachineEventHandler>
@required
-(void)updateState:(BOOL)arg1;
-(void)userWokeUp;
-(void)bedtimeDNDEnabled:(BOOL)arg1 userRequested:(BOOL)arg2 date:(id)arg3;

@end

