/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 8, 2020 at 8:04:12 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Assistant/Plugins/ClientFlowService.assistantBundle/ClientFlowService
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/AFServiceMaintenance.h>

@interface CFBackgroundActionService : NSObject <AFServiceMaintenance>
-(void)performMorphunAssetsManagement:(/*^block*/id)arg1 ;
-(void)performMaintenanceWithCompletion:(/*^block*/id)arg1 ;
@end

