/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:46:05 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/DoNotDisturb.framework/DoNotDisturb
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <DoNotDisturb/DoNotDisturb-Structs.h>
#import <DoNotDisturb/DNDScheduleTimePeriod.h>

@class DNDScheduleTime;

@interface DNDMutableScheduleTimePeriod : DNDScheduleTimePeriod

@property (nonatomic,copy) DNDScheduleTime * startTime; 
@property (nonatomic,copy) DNDScheduleTime * endTime; 
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setEndTime:(DNDScheduleTime *)arg1 ;
-(void)setStartTime:(DNDScheduleTime *)arg1 ;
@end

