/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:57:43 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/VoiceMemos.framework/VoiceMemos
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/RCSAudioFile.h>

@class NSURL, AVAudioFormat, NSDictionary, RCSSavedRecordingAccessToken, NSString;

@interface _RCSAudioFile : NSObject <RCSAudioFile> {

	RCSSavedRecordingAccessToken* _fileToken;

}

@property (nonatomic,retain) RCSSavedRecordingAccessToken * fileToken;              //@synthesize fileToken=_fileToken - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSURL * url; 
@property (nonatomic,readonly) AVAudioFormat * fileFormat; 
@property (nonatomic,readonly) AVAudioFormat * processingFormat; 
@property (nonatomic,readonly) NSDictionary * settings; 
-(NSURL *)url;
-(NSDictionary *)settings;
-(AVAudioFormat *)processingFormat;
-(AVAudioFormat *)fileFormat;
-(RCSSavedRecordingAccessToken *)fileToken;
-(void)setFileToken:(RCSSavedRecordingAccessToken *)arg1 ;
@end

