/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:50:28 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/HomeKitBackingStore.framework/HomeKitBackingStore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <HomeKitBackingStore/HMBModelIndexedQuery.h>

@interface HMBModelFiniteQuery : HMBModelIndexedQuery
+(id)queryWithSQLPredicate:(id)arg1 maximumRowsReturned:(unsigned long long)arg2 indexedProperties:(id)arg3 arguments:(id)arg4 ;
-(id)indexName;
-(id)performQueryOn:(id)arg1 arguments:(id)arg2 ;
@end

