/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:37:38 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface BSUIApplicationSupport : NSObject
+(id)_GSEventPortNameForBundleID:(id)arg1 ;
+(id)generateLaunchJobLabelForBundleID:(id)arg1 ;
+(id)GSEventPortNameForBundleID:(id)arg1 ;
+(id)resolveServiceName:(id)arg1 ;
+(id)defaultMachServicesForBundleID:(id)arg1 ;
+(id)defaultEnvironment;
@end

