/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:53:34 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/RelevanceEngine.framework/RelevanceEngine
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol REBacktrackingTokenBuffer, REScriptParserDelegate;
@interface REScriptParser : NSObject {

	id<REBacktrackingTokenBuffer> _buffer;
	id<REScriptParserDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<REScriptParserDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(id<REScriptParserDelegate>)delegate;
-(void)setDelegate:(id<REScriptParserDelegate>)arg1 ;
-(id)parse;
-(id)initWithBacktrackingBuffer:(id)arg1 ;
@end

