/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:45:54 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/SpringBoardUIServices.framework/SpringBoardUIServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SBUIBiometricResourceObserver <NSObject>
@optional
-(void)biometricResource:(id)arg1 observeEvent:(unsigned long long)arg2;
-(void)biometricResource:(id)arg1 matchingAllowedDidChange:(BOOL)arg2;
-(void)biometricResource:(id)arg1 matchingEnabledDidChange:(BOOL)arg2;

@end

