/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:49:33 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/NewsToday.framework/NewsToday
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsToday/NewsToday-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSDictionary;

@interface NTCatchUpOperationForYouFetchInfo : NSObject <NSCopying> {

	BOOL _attemptedCachedOnly;
	NSDictionary* _feedContextByFeedID;

}

@property (nonatomic,readonly) BOOL attemptedCachedOnly;                             //@synthesize attemptedCachedOnly=_attemptedCachedOnly - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * feedContextByFeedID;              //@synthesize feedContextByFeedID=_feedContextByFeedID - In the implementation block
-(id)init;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSDictionary *)feedContextByFeedID;
-(BOOL)attemptedCachedOnly;
-(id)initWithAttemptedCachedOnly:(BOOL)arg1 feedContextByFeedID:(id)arg2 ;
@end

