/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:48:18 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/MediaPlaybackCore.framework/MediaPlaybackCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface MPCAssistantEncodings : NSObject
-(void)decodeHashedRouteUIDs:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)encodeURLData:(id)arg1 ;
-(id)decodeURLData:(id)arg1 ;
-(void)encodeHashedRouteUIDs:(id)arg1 completion:(/*^block*/id)arg2 ;
@end

