/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 8, 2020 at 8:05:59 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACCAuthContext.h>

@class NSString;

@interface ACMAuthContext : ACCAuthContext {

	NSString* _userPreferences;

}

@property (retain) NSString * userPreferences;              //@synthesize userPreferences=_userPreferences - In the implementation block
-(void)dealloc;
-(void)setUserPreferences:(NSString *)arg1 ;
-(NSString *)userPreferences;
-(id)parametersDictionary;
-(BOOL)isDevicePwnd;
@end

