/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 8, 2020 at 8:06:03 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray, UITableViewCellAccessibilityElement, NSMutableDictionary;

@interface _AXTableViewCellInternal : NSObject {

	NSMutableArray* children;
	BOOL cellOrAncestorHiddenWhileFetchingChildren;
	id removeMinusButton;
	id text;
	id removeConfirmButton;
	id accessoryButton;
	NSMutableArray* mockSubviews;
	UITableViewCellAccessibilityElement* mockParent;
	NSMutableDictionary* _subClassData;
	NSMutableArray* discardedLabels;

}
-(id)init;
@end

