/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 8, 2020 at 8:06:03 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/__UITableViewCellEditControlAccessibility_super.h>

@interface UITableViewCellEditControlAccessibility : __UITableViewCellEditControlAccessibility_super
+(id)safeCategoryTargetClassName;
+(void)_accessibilityPerformValidations:(id)arg1 ;
+(Class)safeCategoryBaseClass;
-(id)accessibilityLabel;
-(id)accessibilityValue;
-(id)accessibilityHint;
-(unsigned long long)accessibilityTraits;
-(BOOL)isAccessibilityElement;
-(BOOL)accessibilityElementsHidden;
-(BOOL)canBecomeFocused;
@end

