/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 8, 2020 at 8:06:03 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/__UITransitionViewAccessibility_super.h>

@interface UITransitionViewAccessibility : __UITransitionViewAccessibility_super
+(id)safeCategoryTargetClassName;
+(void)_accessibilityPerformValidations:(id)arg1 ;
+(Class)safeCategoryBaseClass;
-(BOOL)accessibilityViewIsModal;
-(BOOL)accessibilityPerformEscape;
-(void)_didCompleteTransition:(BOOL)arg1 ;
-(id)_accessibilityHitTestingObscuredScreenAllowedViews;
-(void)_accessibilityLoadAccessibilityInformation;
-(id)_accessibilityRetrieveDelegate;
-(id)_accessibilityDimmingView;
@end

