/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:50:11 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/NewsAnalyticsUpload.framework/NewsAnalyticsUpload
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NDAnalyticsEnvelopeStoreObserver <NSObject>
@required
-(void)envelopeStore:(id)arg1 didFlushEnvelopesForEntries:(id)arg2;

@end

