/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:53:17 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/CertUI.framework/CertUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <CertUI/CertUI-Structs.h>
@interface CertUIUtilities : NSObject
+(id)_certUIBundle;
+(id)bundleIDFromAuditToken:(SCD_Struct_Ce0*)arg1 ;
+(id)localizedAppTitleForBundleID:(id)arg1 ;
@end

