/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:43:22 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/MapKit.framework/MapKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UIPanGestureRecognizer.h>

@interface _MKConditionalPanGestureRecognizer : UIPanGestureRecognizer {

	long long _requiredModifierFlags;

}

@property (assign,nonatomic) long long requiredModifierFlags;              //@synthesize requiredModifierFlags=_requiredModifierFlags - In the implementation block
-(BOOL)_shouldReceiveEvent:(id)arg1 ;
-(long long)requiredModifierFlags;
-(void)setRequiredModifierFlags:(long long)arg1 ;
@end

