/*
* This header is generated by classdump-dyld 1.0
* on Monday, September 7, 2020 at 2:35:17 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface RTSystemControl : NSObject
+(id)valueForKey:(id)arg1 ;
+(id)valueForMib:(int*)arg1 miblen:(int)arg2 ;
+(unsigned long long)sysctlByName:(id)arg1 ;
@end

