/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:37:45 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol _UICollectionLayoutAuxillaryHosting <NSObject>
@optional
-(CGPoint*)auxillaryHostAdditionalFrameOffset;

@required
-(CGSize*)auxillaryHostContentSize;
-(CGSize*)auxillaryHostPinningContentSize;
-(id)auxillaryHostContainer;
-(id)auxillaryHostAuxillaryItems;
-(BOOL)auxillaryHostShouldLayoutRTL;
-(unsigned long long)auxillaryHostLayoutAxis;
-(long long)auxillaryHostAuxillaryKind;
-(id)auxillaryHostSupplementaryEnroller;
-(id)auxillaryHostPreferredSizes;

@end

