/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:37:51 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class _UISearchBarLayout;

@interface _UISearchBarTransitionContext : NSObject {

	_UISearchBarLayout* _toLayout;
	_UISearchBarLayout* _fromLayout;

}

@property (nonatomic,copy) _UISearchBarLayout * toLayout;                //@synthesize toLayout=_toLayout - In the implementation block
@property (nonatomic,copy) _UISearchBarLayout * fromLayout;              //@synthesize fromLayout=_fromLayout - In the implementation block
-(_UISearchBarLayout *)fromLayout;
-(_UISearchBarLayout *)toLayout;
-(void)setFromLayout:(_UISearchBarLayout *)arg1 ;
-(void)setToLayout:(_UISearchBarLayout *)arg1 ;
@end

