/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:38:33 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UIKitCore-Structs.h>
#import <UIKitCore/_UITextCanvasView.h>

@interface _UITextFieldCanvasView : _UITextCanvasView

@property (assign,nonatomic,__weak) id<_UITextFieldCanvasViewContext> context; 
-(void)drawRect:(CGRect)arg1 ;
-(BOOL)_enableAutoConstraining;
-(void)drawTextInRect:(CGRect)arg1 ;
@end

