/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:37:54 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class UIColor;


@protocol UICollectionViewTableAttributes <UICollectionViewTableSeparatorAttributes>
@property (nonatomic,copy) UIColor * backgroundColor; 
@required
-(UIColor *)backgroundColor;
-(void)setBackgroundColor:(id)arg1;

@end

