/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:38:39 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <UIKitCore/UIKitCore-Structs.h>
@interface UIFloatCompoundSpringIntegrator : NSObject
+(SCD_Struct_UI130)integrateWithState:(SCD_Struct_UI130)arg1 springParameters:(SCD_Struct_UI128)arg2 deltaTime:(double)arg3 ;
+(SCD_Struct_UI129)advanceParametersWithState:(SCD_Struct_UI129)arg1 springParameters:(SCD_Struct_UI128)arg2 deltaTime:(double)arg3 ;
@end

