/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:38:13 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UIKitCore-Structs.h>
#import <UIKitCore/UIKBRenderFactoryiPad.h>

@interface UIKBRenderFactoryiPadSplit : UIKBRenderFactoryiPad
-(id)backgroundTraitsForKeyplane:(id)arg1 ;
-(double)keyCornerRadius;
-(id)_traitsForKey:(id)arg1 onKeyplane:(id)arg2 ;
-(id)deleteKeyImageName;
-(id)deleteOnKeyImageName;
-(id)shiftKeyImageName;
-(id)shiftLockImageName;
-(id)shiftOnKeyImageName;
-(double)skinnyKeyThreshold;
-(id)globalEmojiKeyImageName;
-(id)globalKeyImageName;
-(id)dismissKeyImageName;
-(id)dictationKeyImageName;
-(id)multitapCompleteKeyImageName;
-(id)muttitapReverseKeyImageName;
-(BOOL)supportsInputTraits:(id)arg1 forKeyplane:(id)arg2 ;
-(void)_customizeTraits:(id)arg1 forPopupForKey:(id)arg2 withRenderingContext:(id)arg3 keycapsFontName:(id)arg4 ;
-(CGPoint)internationalKeyOffset;
-(CGPoint)deleteKeyOffset;
-(CGPoint)shiftKeyOffset;
-(CGPoint)dismissKeyOffset;
-(double)variantAnnotationTextFontSize;
-(CGPoint)variantAnnotationTextOffset;
-(id)variantGeometriesForGeometry:(id)arg1 variantCount:(unsigned long long)arg2 rowLimit:(long long)arg3 annotationIndex:(unsigned long long)arg4 ;
-(void)_customizeSymbolStyle:(id)arg1 forKey:(id)arg2 contents:(id)arg3 ;
-(void)_customizeGeometry:(id)arg1 forKey:(id)arg2 contents:(id)arg3 ;
-(double)keyInsetBottom;
-(double)symbolFrameInset;
-(double)defaultPathWeight;
@end

