/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:38:12 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UIKeyboardInputMode.h>

@interface UISpecializedInputMode : UIKeyboardInputMode {

	Class _viewControllerClass;

}

@property (nonatomic,retain) Class viewControllerClass;              //@synthesize viewControllerClass=_viewControllerClass - In the implementation block
-(void)dealloc;
-(BOOL)isSpecializedInputMode;
-(id)hardwareLayout;
-(void)setViewControllerClass:(Class)arg1 ;
-(BOOL)includeBarHeight;
-(Class)viewControllerClass;
@end

