/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:37:51 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UITabBarItem, UITabBarButton;

@interface UITabBarItemProxy : NSObject {

	UITabBarItem* _item;
	UITabBarButton* _view;

}
-(id)item;
-(id)view;
-(void)setSelected:(BOOL)arg1 ;
-(id)initWithItem:(id)arg1 inTabBar:(id)arg2 ;
@end

