/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:43:08 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/AppSupportUI.framework/AppSupportUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AppSupportUI/AppSupportUI-Structs.h>
#import <UIKitCore/UITableViewCell.h>

@class NUIContainerView;

@interface NUITableViewContainerCell : UITableViewCell {

	NUIContainerView* _containerView;

}

@property (nonatomic,readonly) NUIContainerView * containerView;              //@synthesize containerView=_containerView - In the implementation block
+(Class)containerViewClass;
-(NUIContainerView *)containerView;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
@end

