/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:40:00 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/HMFoundation.framework/HMFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <HMFoundation/__HMFMessageHandler.h>

@interface __HMFBlockMessageHandler : __HMFMessageHandler {

	/*^block*/id _handler;

}

@property (copy,readonly) id handler;              //@synthesize handler=_handler - In the implementation block
-(id)handler;
-(BOOL)invokeWithMessage:(id)arg1 ;
@end

