/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:40:01 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/HMFoundation.framework/HMFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <HMFoundation/HMFObject.h>

@class HMFUnfairLock, NSMutableDictionary;

@interface HMFClassRegistry : HMFObject {

	HMFUnfairLock* _lock;
	NSMutableDictionary* _classes;
	Class _defaultClass;

}

@property (readonly) Class defaultClass;              //@synthesize defaultClass=_defaultClass - In the implementation block
-(id)init;
-(id)initWithDefaultClass:(Class)arg1 ;
-(Class)classForKey:(id)arg1 ;
-(void)setClass:(Class)arg1 forKey:(id)arg2 ;
-(Class)defaultClass;
@end

