/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:46:40 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/Email.framework/Email
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol EMAccountRepositoryObserver <NSObject>
@required
-(void)accountsAdded:(id)arg1;
-(void)accountsRemoved:(id)arg1;
-(void)accountsChanged:(id)arg1;
-(void)didBeginObserving;
-(void)didEndObserving;

@end

