/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:56:23 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/OIXMLNode.h>

@class OIXMLElement, NSString;

@interface OIXMLDocument : OIXMLNode {

	OIXMLElement* _rootElement;
	NSString* _version;
	NSString* _encoding;

}

@property (retain) OIXMLElement * rootElement;              //@synthesize rootElement=_rootElement - In the implementation block
@property (copy) NSString * version;                        //@synthesize version=_version - In the implementation block
@property (copy) NSString * characterEncoding;              //@synthesize encoding=_encoding - In the implementation block
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)version;
-(void)setVersion:(NSString *)arg1 ;
-(id)contentString;
-(void)setRootElement:(OIXMLElement *)arg1 ;
-(OIXMLElement *)rootElement;
-(id)initWithRootElement:(id)arg1 ;
-(id)openingTagString;
-(id)XMLString;
-(id)closingTagString;
-(void)setCharacterEncoding:(NSString *)arg1 ;
-(NSString *)characterEncoding;
-(id)createMutableXMLString;
@end

