/*
* This header is generated by classdump-dyld 1.0
* on Monday, September 7, 2020 at 2:30:13 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /usr/lib/libusrtcp.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libdispatch.dylib/OS_object.h>

@interface OS_nw_protocol_tcp : OS_object
-(void)dealloc;
@end

