/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:50:25 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/MPUFoundation.framework/MPUFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol _UIBasicAnimationFactory <NSObject>
@optional
-(id)_timingFunctionForAnimation;
-(id)_timingFunctionForAnimationInView:(id)arg1 withKeyPath:(id)arg2;
-(BOOL)_shouldAnimateAdditivelyForView:(id)arg1 withKeyPath:(id)arg2;

@required
-(id)_basicAnimationForView:(id)arg1 withKeyPath:(id)arg2;

@end

