/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:53:10 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/iCalendar.framework/iCalendar
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSNumber.h>

@interface ICSPredefinedValue : NSNumber {

	long long _value;

}
+(BOOL)supportsSecureCoding;
+(id)numberWithLong:(long long)arg1 ;
-(id)initWithLong:(long long)arg1 ;
-(const char*)objCType;
-(long long)longValue;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(Class)classForCoder;
-(void)getValue:(void*)arg1 ;
-(id)initWithBytes:(const void*)arg1 objCType:(const char*)arg2 ;
@end

