/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:56:17 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/MobileTimerUI.framework/MobileTimerUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileTimerUI/MobileTimerUI-Structs.h>
#import <MobileTimerUI/MTUIDateLabel.h>

@class NSCalendar, NSDate;

@interface MTUIDigitalClockLabel : MTUIDateLabel {

	NSCalendar* _calendar;
	NSDate* _baseDate;
	long long _hour;
	long long _minute;

}
-(id)initWithFrame:(CGRect)arg1 ;
-(BOOL)setHour:(long long)arg1 minute:(long long)arg2 ;
-(void)significantTimeChange:(id)arg1 ;
-(void)refreshUI;
-(void)resetFontSizes;
-(void)forceSetHour:(long long)arg1 minute:(long long)arg2 ;
-(void)setTimeLabelText:(id)arg1 ;
@end

