/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:46:02 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/Metal.framework/Metal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Metal/Metal-Structs.h>
@interface MTLResourceList : NSObject {

	SCD_Struct_MT69* _listPriv;

}
-(void)dealloc;
-(id)initWithCapacity:(int)arg1 ;
-(void)releaseAllObjectsAndReset;
@end

