/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:52:20 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/HealthAlgorithms.framework/HealthAlgorithms
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SRMultiSampleExporting <NSObject>
@required
-(void)sr_beginMultiSampleStream;
-(id)sr_endMultiSampleStream;
-(id)sr_dictionaryRepresentationWithSample:(id)arg1;

@end

