/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:48:44 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SearchUITLKMultilineTextConverter : NSObject
+(id)richTextForSearchUIText:(id)arg1 ;
+(id)textForSearchUIText:(id)arg1 ;
+(id)richTextForSearchUIText:(id)arg1 withCompletionHandler:(/*^block*/id)arg2 ;
+(BOOL)richTextOverridesAsyncLoader:(id)arg1 ;
+(void)applyRichText:(id)arg1 toTLKRichText:(id)arg2 ;
+(id)formattedTextForSearchUIText:(id)arg1 ;
+(id)textForSearchUIString:(id)arg1 ;
@end

