/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:54:29 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/VisionKit.framework/VisionKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <VisionKit/VNDocumentCameraViewController.h>
#import <libobjc.A.dylib/ICDocCamViewControllerDelegate.h>

@class ICDocCamViewController, NSString;

@interface VNDocumentCameraViewController_InProcess : VNDocumentCameraViewController <ICDocCamViewControllerDelegate> {

	ICDocCamViewController* _viewController;

}

@property (nonatomic,retain) ICDocCamViewController * viewController;              //@synthesize viewController=_viewController - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(void)setViewController:(ICDocCamViewController *)arg1 ;
-(ICDocCamViewController *)viewController;
-(long long)_preferredModalPresentationStyle;
-(void)_autoDismiss;
-(void)didReceiveMemoryWarning;
-(BOOL)documentCameraController:(id)arg1 canAddImages:(unsigned long long)arg2 ;
-(void)documentCameraControllerDidCancel:(id)arg1 ;
-(id)documentCameraControllerCreateDataCryptorIfNecessary;
-(id)scanDataDelegateWithIdentifier:(id)arg1 ;
-(void)documentCameraController:(id)arg1 didFinishWithImage:(id)arg2 ;
-(void)documentCameraController:(id)arg1 didFinishWithDocInfoCollection:(id)arg2 imageCache:(id)arg3 warnUser:(BOOL)arg4 ;
@end

