/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:38:14 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class AFPreferences;

@interface UIDictationConnectionPreferences : NSObject {

	AFPreferences* _afPreferences;

}

@property (nonatomic,retain) AFPreferences * afPreferences;              //@synthesize afPreferences=_afPreferences - In the implementation block
+(id)sharedInstance;
-(id)languageCode;
-(BOOL)dictationIsEnabled;
-(id)initSingleton;
-(void)afPreferencesChanged:(id)arg1 ;
-(BOOL)suppressDictationOptIn;
-(BOOL)ignoreServerManualEndpointingThreshold;
-(id)manualEndpointingThreshold;
-(long long)dataSharingOptInStatus;
-(BOOL)suppressDataSharingOptIn;
-(id)dictationSLSEnabledLanguages;
-(AFPreferences *)afPreferences;
-(void)setAfPreferences:(AFPreferences *)arg1 ;
@end

