/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:52:36 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/MobileStoreDemoKit.framework/MobileStoreDemoKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary;

@interface MSDLocalization : NSObject {

	NSDictionary* _localizationTable;

}

@property (nonatomic,retain) NSDictionary * localizationTable;              //@synthesize localizationTable=_localizationTable - In the implementation block
+(id)sharedInstance;
+(id)getLocalizedOwnershipWarnings;
-(id)init;
-(NSDictionary *)localizationTable;
-(id)localizedStringWithKey:(id)arg1 defaultString:(id)arg2 ;
-(void)setLocalizationTable:(NSDictionary *)arg1 ;
@end

