/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:56:44 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/PhotosGraph.framework/PhotosGraph
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <PhotosGraph/PhotosGraph-Structs.h>
#import <PhotosGraph/PGGraphEdge.h>

@class NSDate, CLLocation;

@interface PGGraphAddressEdge : PGGraphEdge

@property (nonatomic,readonly) double timestampUTCStart; 
@property (nonatomic,readonly) double timestampUTCEnd; 
@property (nonatomic,readonly) NSDate * universalStartDate; 
@property (nonatomic,readonly) NSDate * universalEndDate; 
@property (nonatomic,readonly) CLLocationCoordinate2D photoCoordinate; 
@property (nonatomic,readonly) CLLocation * photoLocation; 
-(NSDate *)universalStartDate;
-(NSDate *)universalEndDate;
-(double)timestampUTCStart;
-(double)timestampUTCEnd;
-(CLLocationCoordinate2D)photoCoordinate;
-(CLLocation *)photoLocation;
@end

