/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:54:12 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/BehaviorMiner.framework/BehaviorMiner
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <BehaviorMiner/BehaviorMiner-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class BMItemType, NSString;

@interface BMItem : NSObject <NSCopying> {

	BMItemType* _type;
	NSString* _normalizedValue;

}

@property (nonatomic,retain) BMItemType * type;                     //@synthesize type=_type - In the implementation block
@property (nonatomic,copy) NSString * normalizedValue;              //@synthesize normalizedValue=_normalizedValue - In the implementation block
@property (nonatomic,copy,readonly) id value; 
+(id)itemWithType:(id)arg1 stringValue:(id)arg2 ;
+(id)itemWithType:(id)arg1 numberValue:(id)arg2 ;
+(id)itemWithType:(id)arg1 UUIDValue:(id)arg2 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BMItemType *)type;
-(void)setType:(BMItemType *)arg1 ;
-(id)value;
-(id)initWithType:(id)arg1 value:(id)arg2 ;
-(NSString *)normalizedValue;
-(void)setNormalizedValue:(NSString *)arg1 ;
-(id)initWithType:(id)arg1 normalizedValue:(id)arg2 ;
-(id)uniformIdentifier;
@end

