/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:37:44 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <UIFoundation/UIFoundation-Structs.h>
@interface _NSTextStorageSideData : NSObject {

	id _delegate;
	NSRange _lazyFixRange;

}

@property (__weak) id delegate; 
-(void)dealloc;
-(id)delegate;
-(void)setDelegate:(id)arg1 ;
@end

