/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:52:17 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/RunningBoard.framework/RunningBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/RBStateCaptureManaging.h>

@protocol OS_dispatch_queue;
@class NSMutableDictionary, RBSStateCaptureSet, NSObject, NSString;

@interface RBStateCaptureManager : NSObject <RBStateCaptureManaging> {

	NSMutableDictionary* _itemsByIdentifier;
	RBSStateCaptureSet* _itemsWithoutIdentifiers;
	NSObject*<OS_dispatch_queue> _queue;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(void)removeItem:(id)arg1 ;
-(void)addItem:(id)arg1 ;
-(id)identifiers;
-(id)stateForSubsystem:(id)arg1 ;
-(void)addItemWithTitle:(id)arg1 identifier:(id)arg2 block:(/*^block*/id)arg3 ;
-(void)removeItemWithIdentifier:(id)arg1 ;
-(void)addItem:(id)arg1 withIdentifier:(id)arg2 ;
@end

