/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:54:39 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/AccessoryNavigation.framework/AccessoryNavigation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary;

@interface ACCNavigationRoadObjectRoadSignInfo : NSObject {

	NSMutableDictionary* _infoDict;

}

@property (retain) NSMutableDictionary * infoDict;              //@synthesize infoDict=_infoDict - In the implementation block
+(id)keyForType:(unsigned short)arg1 ;
-(id)init;
-(id)description;
-(id)copyDictionary;
-(BOOL)_checkDataClassForType:(unsigned short)arg1 data:(id)arg2 ;
-(id)copyInfo:(unsigned short)arg1 ;
-(BOOL)setInfo:(unsigned short)arg1 data:(id)arg2 ;
-(NSMutableDictionary *)infoDict;
-(void)setInfoDict:(NSMutableDictionary *)arg1 ;
-(void)setInfoFromDictionary:(id)arg1 ;
@end

