/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:55:47 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class HKGraphSeries, HKDisplayType, UIColor;

@interface HKGraphSeriesConfiguration : NSObject {

	HKGraphSeries* _graphSeries;
	HKDisplayType* _displayType;
	UIColor* _tintColor;

}

@property (nonatomic,retain) HKGraphSeries * graphSeries;              //@synthesize graphSeries=_graphSeries - In the implementation block
@property (nonatomic,retain) HKDisplayType * displayType;              //@synthesize displayType=_displayType - In the implementation block
@property (nonatomic,retain) UIColor * tintColor;                      //@synthesize tintColor=_tintColor - In the implementation block
-(HKDisplayType *)displayType;
-(void)setDisplayType:(HKDisplayType *)arg1 ;
-(UIColor *)tintColor;
-(void)setTintColor:(UIColor *)arg1 ;
-(HKGraphSeries *)graphSeries;
-(void)setGraphSeries:(HKGraphSeries *)arg1 ;
@end

