/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:55:43 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol HKChartCacheDataSource;
@class NSString;

@interface HKInteractiveChartOverlayNamedDataSource : NSObject {

	id<HKChartCacheDataSource> _dataSource;
	NSString* _name;
	/*^block*/id _contextTitleForTimeScope;

}

@property (nonatomic,retain) id<HKChartCacheDataSource> dataSource;              //@synthesize dataSource=_dataSource - In the implementation block
@property (nonatomic,retain) NSString * name;                                    //@synthesize name=_name - In the implementation block
@property (nonatomic,copy) id contextTitleForTimeScope;                          //@synthesize contextTitleForTimeScope=_contextTitleForTimeScope - In the implementation block
-(NSString *)name;
-(void)setName:(NSString *)arg1 ;
-(id<HKChartCacheDataSource>)dataSource;
-(void)setDataSource:(id<HKChartCacheDataSource>)arg1 ;
-(id)contextTitleForTimeScope;
-(id)initWithDataSource:(id)arg1 named:(id)arg2 withContextTitleForTimeScope:(/*^block*/id)arg3 ;
-(void)setContextTitleForTimeScope:(id)arg1 ;
@end

