/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:53:11 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/BluetoothAudio.framework/BluetoothAudio
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct OpaqueFigEndpointManager* OpaqueFigEndpointManagerRef;

typedef struct BTSessionImpl* BTSessionImplRef;

typedef struct BTDeviceImpl* BTDeviceImplRef;

typedef struct __CFDictionary* CFDictionaryRef;

