/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:53:29 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/MobileMailUI.framework/MobileMailUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMailUI/MobileMailUI-Structs.h>
#import <MobileMailUI/MFSuggestionBannerView.h>

@protocol MFBlockedSenderBannerViewDelegate;
@interface MFBlockedSenderBannerView : MFSuggestionBannerView {

	id<MFBlockedSenderBannerViewDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<MFBlockedSenderBannerViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(id<MFBlockedSenderBannerViewDelegate>)delegate;
-(void)setDelegate:(id<MFBlockedSenderBannerViewDelegate>)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)_titleControlTapped:(id)arg1 ;
-(void)_bannerDismissed:(id)arg1 ;
@end

