/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:48:55 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/SXAdResponse.h>

@protocol SXPrerollAdMetadata;
@class NSURL;

@interface SXPrerollAdResponse : SXAdResponse {

	NSURL* _videoURL;
	double _skipDuration;
	id<SXPrerollAdMetadata> _prerollAdMetadata;

}

@property (nonatomic,retain) NSURL * videoURL;                                       //@synthesize videoURL=_videoURL - In the implementation block
@property (assign,nonatomic) double skipDuration;                                    //@synthesize skipDuration=_skipDuration - In the implementation block
@property (nonatomic,retain) id<SXPrerollAdMetadata> prerollAdMetadata;              //@synthesize prerollAdMetadata=_prerollAdMetadata - In the implementation block
-(NSURL *)videoURL;
-(void)setVideoURL:(NSURL *)arg1 ;
-(double)skipDuration;
-(void)setSkipDuration:(double)arg1 ;
-(void)setPrerollAdMetadata:(id<SXPrerollAdMetadata>)arg1 ;
-(id<SXPrerollAdMetadata>)prerollAdMetadata;
@end

