/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:52:02 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/TVRemoteUI.framework/TVRemoteUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol _TVRAlertControllerDelegate <NSObject>
@required
-(void)alertController:(id)arg1 enteredText:(id)arg2;
-(void)alertControllerPressedDictationButton:(id)arg1;
-(void)alertControllerReleasedDictationButton:(id)arg1;
-(void)alertControllerCancelled:(id)arg1;
-(void)alertControllerHitKeyboardReturnKey:(id)arg1;
-(void)alertController:(id)arg1 generatedTextInputPayload:(id)arg2;

@end

