/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:53:38 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/BulletinDistributorCompanion.framework/BulletinDistributorCompanion
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString;


@protocol BLTPingSubscriptionInfo <NSObject>
@property (nonatomic,copy,readonly) NSString * sectionID; 
@property (nonatomic,readonly) BOOL forBulletin; 
@property (nonatomic,readonly) BOOL canAck; 
@property (nonatomic,readonly) BOOL canAckOnLocalConnection; 
@required
-(NSString *)sectionID;
-(BOOL)canAck;
-(BOOL)forBulletin;
-(BOOL)canAckOnLocalConnection;

@end

