/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:57:46 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/RTCVideoEncoderFactory.h>

@class WK_RTCVideoCodecInfo, NSString;

@interface WK_RTCDefaultVideoEncoderFactory : NSObject <RTCVideoEncoderFactory> {

	WK_RTCVideoCodecInfo* preferredCodec;

}

@property (nonatomic,retain) WK_RTCVideoCodecInfo * preferredCodec; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)supportedCodecs;
-(WK_RTCVideoCodecInfo *)preferredCodec;
-(void)setPreferredCodec:(WK_RTCVideoCodecInfo *)arg1 ;
-(id)supportedCodecs;
-(id)createEncoder:(id)arg1 ;
@end

