/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:43:30 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Celestial/BWStillImageProcessorConfiguration.h>

@class BWVideoFormat, BWInferenceScheduler;

@interface BWUBInferenceControllerConfiguration : BWStillImageProcessorConfiguration {

	BWVideoFormat* _inputFormat;
	unsigned _figThreadPriority;
	BOOL _semanticRenderingEnabled;
	BOOL _redEyeReductionEnabled;
	BWInferenceScheduler* _inferenceScheduler;

}

@property (nonatomic,retain) BWVideoFormat * inputFormat;                            //@synthesize inputFormat=_inputFormat - In the implementation block
@property (assign,nonatomic) unsigned figThreadPriority;                             //@synthesize figThreadPriority=_figThreadPriority - In the implementation block
@property (assign,nonatomic) BOOL semanticRenderingEnabled;                          //@synthesize semanticRenderingEnabled=_semanticRenderingEnabled - In the implementation block
@property (assign,nonatomic) BOOL redEyeReductionEnabled;                            //@synthesize redEyeReductionEnabled=_redEyeReductionEnabled - In the implementation block
@property (nonatomic,retain) BWInferenceScheduler * inferenceScheduler;              //@synthesize inferenceScheduler=_inferenceScheduler - In the implementation block
-(void)dealloc;
-(BOOL)redEyeReductionEnabled;
-(BWVideoFormat *)inputFormat;
-(void)setFigThreadPriority:(unsigned)arg1 ;
-(BOOL)semanticRenderingEnabled;
-(void)setSemanticRenderingEnabled:(BOOL)arg1 ;
-(void)setInferenceScheduler:(BWInferenceScheduler *)arg1 ;
-(void)setRedEyeReductionEnabled:(BOOL)arg1 ;
-(void)setInputFormat:(BWVideoFormat *)arg1 ;
-(unsigned)figThreadPriority;
-(BWInferenceScheduler *)inferenceScheduler;
@end

