/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:45:09 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/PencilKit.framework/PencilKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PKInkModifier : NSObject
+(id)dictionaryForInk:(id)arg1 name:(id)arg2 ;
+(void)addFunction:(id)arg1 forInk:(id)arg2 ;
+(void)removeFunction:(id)arg1 forInk:(id)arg2 ;
+(void)functionDidChange:(id)arg1 forInk:(id)arg2 ;
+(void)modifyInk:(id)arg1 withValue:(double)arg2 forProperty:(id)arg3 ;
+(void)clearInkManagerCache;
@end

