/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:50:16 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/CommunicationsSetupUI.framework/CommunicationsSetupUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CommunicationsSetupUI/CNFRegTableLabel.h>

@interface CNFRegTableFooterLabel : CNFRegTableLabel
-(double)_topPadding;
-(double)_bottomPadding;
-(id)_labelText;
-(id)initWithSpecifier:(id)arg1 ;
-(long long)_labelTextAlignment;
-(id)_URLTarget;
-(id)_URLText;
@end

