/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:54:56 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/BookDataStore.framework/BookDataStore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <BookDataStore/BCMutableCloudData.h>
#import <libobjc.A.dylib/BCGlobalMetadatum.h>

@class NSString, NSDate, CKRecord, NSData;

@interface BCMutableGlobalMetadatum : BCMutableCloudData <BCGlobalMetadatum> {

	NSString* _key;
	NSString* _value;

}

@property (nonatomic,copy) NSString * value;                                                     //@synthesize value=_value - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) BOOL deletedFlag; 
@property (nonatomic,copy,readonly) NSDate * modificationDate; 
@property (nonatomic,readonly) long long editGeneration; 
@property (nonatomic,readonly) long long syncGeneration; 
@property (nonatomic,copy,readonly) CKRecord * systemFields; 
@property (nonatomic,copy,readonly) NSData * ckSystemFields; 
@property (assign,nonatomic,__weak) id<BCCloudDataPrivacyDelegate> privacyDelegate; 
@property (nonatomic,copy,readonly) NSString * key;                                              //@synthesize key=_key - In the implementation block
-(NSString *)description;
-(NSString *)key;
-(id)identifier;
-(NSString *)value;
-(void)setValue:(NSString *)arg1 ;
-(id)initWithKey:(id)arg1 ;
-(id)recordType;
-(id)zoneName;
-(id)initWithRecord:(id)arg1 ;
-(id)initWithCloudData:(id)arg1 ;
-(id)configuredRecordFromAttributes;
@end

