/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:45:06 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/AnnotationKit.framework/AnnotationKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AnnotationKit/AKAdornmentLayer.h>

@class CAShapeLayer;

@interface AKCropAdornmentLayer : AKAdornmentLayer {

	CAShapeLayer* _handlesLayer;

}

@property (retain) CAShapeLayer * handlesLayer;              //@synthesize handlesLayer=_handlesLayer - In the implementation block
-(void)updateAdornmentElements;
-(void)updateSublayersWithScale:(double)arg1 ;
-(BOOL)needsUpdateWhenDraggingStartsOrEnds;
-(CAShapeLayer *)handlesLayer;
-(void)_addHandles;
-(void)_updateHandles;
-(BOOL)_shouldShowHandles;
-(void)_removeHandles;
-(void)setHandlesLayer:(CAShapeLayer *)arg1 ;
@end

