/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:44:34 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class IKCSSRuleList;

@interface IKCSSStylesheet : NSObject {

	IKCSSRuleList* _ruleList;

}

@property (nonatomic,retain) IKCSSRuleList * ruleList;              //@synthesize ruleList=_ruleList - In the implementation block
-(id)description;
-(IKCSSRuleList *)ruleList;
-(void)setRuleList:(IKCSSRuleList *)arg1 ;
@end

