/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:44:00 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/SafariServices.framework/SafariServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol _SFDialogViewPresenting <NSObject>
@required
-(int)webProcessIDForDialogController:(id)arg1;
-(void)presentDialogView:(id)arg1 withAdditionalAnimations:(/*^block*/id)arg2 forDialogController:(id)arg3;
-(void)dismissDialogView:(id)arg1 withAdditionalAnimations:(/*^block*/id)arg2 forDialogController:(id)arg3;

@end

