/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:45:24 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/ContactsAutocompleteUI.framework/ContactsAutocompleteUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface CNComposeRecipientOriginContext : NSObject {

	NSString* _searchTerm;
	unsigned long long _resultType;

}

@property (nonatomic,retain) NSString * searchTerm;                      //@synthesize searchTerm=_searchTerm - In the implementation block
@property (assign,nonatomic) unsigned long long resultType;              //@synthesize resultType=_resultType - In the implementation block
-(unsigned long long)resultType;
-(void)setResultType:(unsigned long long)arg1 ;
-(NSString *)searchTerm;
-(void)setSearchTerm:(NSString *)arg1 ;
@end

