/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 8, 2020 at 8:06:04 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/AccessibilityBundles/AccessibilitySettingsLoader.bundle/AccessibilitySettingsLoader
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AccessibilitySettingsLoader/__MPAVOutputDeviceRoutingDataSourceAccessibility_super.h>

@interface MPAVOutputDeviceRoutingDataSourceAccessibility : __MPAVOutputDeviceRoutingDataSourceAccessibility_super
+(id)safeCategoryTargetClassName;
+(void)_accessibilityPerformValidations:(id)arg1 ;
+(Class)safeCategoryBaseClass;
-(void)setPickedRoute:(id)arg1 withPassword:(id)arg2 completion:(/*^block*/id)arg3 ;
@end

