/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:50:17 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/Home.framework/Home
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol HFExecutionEnvironmentObserver <NSObject>
@optional
-(void)executionEnvironmentRunningStateDidChange:(id)arg1;
-(void)executionEnvironmentWillEnterForeground:(id)arg1;
-(void)executionEnvironmentDidBecomeActive:(id)arg1;
-(void)executionEnvironmentWillResignActive:(id)arg1;
-(void)executionEnvironmentDidEnterBackground:(id)arg1;
-(void)executionEnvironmentDidBecomeVisible:(id)arg1;
-(void)executionEnvironmentDidBecomeOccluded:(id)arg1;
-(void)executionEnvironmentDidBecomeScreenLocked:(id)arg1;

@end

