/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:40:35 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/OnBoardingKit.framework/OnBoardingKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <OnBoardingKit/OnBoardingKit-Structs.h>
#import <UIKitCore/UIViewController.h>

@interface OBBaseWelcomeController : UIViewController {

	unsigned long long _templateType;

}

@property (assign,nonatomic) unsigned long long templateType;              //@synthesize templateType=_templateType - In the implementation block
+(CGSize)preferredContentSize;
-(void)loadView;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(NSDirectionalEdgeInsets)directionalLayoutMargins;
-(id)navigationItem;
-(unsigned long long)templateType;
-(void)setTemplateType:(unsigned long long)arg1 ;
-(void)updateDirectionalLayoutMargins;
-(long long)navigationBarScrollToEdgeBehavior;
-(void)_applyChromelessToBar:(long long)arg1 navigationItem:(id)arg2 ;
-(void)_presentationStyleValidationCheck;
-(NSDirectionalEdgeInsets)insetsForTemplateType:(unsigned long long)arg1 ;
-(double)autoScrollEdgeTransitionDistance;
@end

