/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:54:07 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/SettingsCellularUI.framework/SettingsCellularUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SettingsCellularUI/PSUIDanglingPlanTableCell.h>

@class UIImageView, CTCellularPlanPendingTransfer;

@interface PSUIPlanPendingTransferTableCell : PSUIDanglingPlanTableCell {

	UIImageView* _view;
	CTCellularPlanPendingTransfer* _planPendingTransfer;

}

@property (nonatomic,retain) UIImageView * view;                                               //@synthesize view=_view - In the implementation block
@property (nonatomic,retain) CTCellularPlanPendingTransfer * planPendingTransfer;              //@synthesize planPendingTransfer=_planPendingTransfer - In the implementation block
-(UIImageView *)view;
-(void)setView:(UIImageView *)arg1 ;
-(void)refreshCellContentsWithSpecifier:(id)arg1 ;
-(void)_setView;
-(CTCellularPlanPendingTransfer *)planPendingTransfer;
-(void)setPlanPendingTransfer:(CTCellularPlanPendingTransfer *)arg1 ;
@end

