/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:52:06 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/CoverSheet.framework/CoverSheet
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol BSUIScrollViewDelegate <UIScrollViewDelegate>
@optional
-(void)scrollViewDidScroll:(id)arg1 withContext:(SCD_Struct_CS9)arg2;
-(void)scrollViewWillBeginScrolling:(id)arg1;
-(void)scrollViewDidEndScrolling:(id)arg1;

@end

