/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:48:42 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/Widgets.framework/Widgets
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol WGWidgetHostingViewControllerHost <NSObject>
@optional
-(long long)userSpecifiedDisplayModeForWidget:(id)arg1;
-(void)widget:(id)arg1 didChangeUserSpecifiedDisplayMode:(long long)arg2;
-(long long)largestAvailableDisplayModeForWidget:(id)arg1;
-(void)widget:(id)arg1 didChangeLargestAvailableDisplayMode:(long long)arg2;
-(void)widget:(id)arg1 didEncounterProblematicSnapshotAtURL:(id)arg2;
-(void)widget:(id)arg1 didRemoveSnapshotAtURL:(id)arg2;
-(BOOL)shouldPurgeArchivedSnapshotsForWidget:(id)arg1;
-(BOOL)shouldPurgeNonCAMLSnapshotsForWidget:(id)arg1;
-(BOOL)shouldPurgeNonASTCSnapshotsForWidget:(id)arg1;
-(BOOL)shouldRemoveSnapshotWhenNotVisibleForWidget:(id)arg1;

@end

