/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:57:15 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/TVRemoteCore.framework/TVRemoteCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSArray;


@protocol TVRMSDiscoverySession <NSObject>
@property (assign,nonatomic,__weak) id<TVRMSDiscoverySessionDelegate> delegate; 
@property (assign,nonatomic) long long discoveryTypes; 
@property (nonatomic,readonly) NSArray * availableServices; 
@property (getter=isNetworkAvailable,nonatomic,readonly) BOOL networkAvailable; 
@property (nonatomic,retain) NSArray * pairedNetworkNames; 
@required
-(id<TVRMSDiscoverySessionDelegate>)delegate;
-(void)setDelegate:(id)arg1;
-(void)endDiscovery;
-(void)beginDiscovery;
-(BOOL)isNetworkAvailable;
-(NSArray *)availableServices;
-(long long)discoveryTypes;
-(void)setDiscoveryTypes:(long long)arg1;
-(NSArray *)pairedNetworkNames;
-(void)setPairedNetworkNames:(id)arg1;

@end

