/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:54:28 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/VisionKit.framework/VisionKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CAAnimationDelegate <NSObject>
@optional
-(void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
-(void)animationDidStart:(id)arg1;

@end

