/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:40:05 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/Contacts.framework/Contacts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CNCDContainerPredicate <NSObject>
@optional
-(id)cn_secondaryRecursePredicate;

@required
-(id)cn_coreDataPredicate;
-(id)cn_topLevelFilter;
-(id)cn_persistenceFilterRequest;

@end

