/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:52:05 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/CoverSheet.framework/CoverSheet
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CSModalViewDelegate <SBLockScreenModalViewDelegate>
@required
-(BOOL)isPortrait;
-(void)handlePrimaryActionForView:(id)arg1;
-(void)handleSecondaryActionForView:(id)arg1;

@end

