/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:49:44 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/TSReading.framework/TSReading
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CALayerDelegate <NSObject>
@optional
-(void)layoutSublayersOfLayer:(id)arg1;
-(void)displayLayer:(id)arg1;
-(void)drawLayer:(id)arg1 inContext:(CGContextRef)arg2;
-(void)layerWillDraw:(id)arg1;
-(id)actionForLayer:(id)arg1 forKey:(id)arg2;

@end

