/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:48:28 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/TeaFoundation.framework/TeaFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface _TtC13TeaFoundationP33_3E775B95AA8F4C6167C1B13E33C411A69Localized : _UKNOWN_SUPERCLASS_
@end

