/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:40:51 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary;

@interface PLQueryChangeDetectionCriteria : NSObject {

	NSMutableDictionary* _attributeKeyPathsByEntityNameAffectingFetchResult;
	NSMutableDictionary* _relationshipKeyPathsByEntityNameAffectingFetchResult;

}

@property (readonly) BOOL isEmpty; 
-(id)init;
-(id)description;
-(BOOL)isEmpty;
-(void)addAttributeKeyPath:(id)arg1 forEntityName:(id)arg2 ;
-(void)addRelationshipKeyPath:(id)arg1 forEntityName:(id)arg2 ;
-(void)enumerateEntitiesAndAttributesUsingBlock:(/*^block*/id)arg1 ;
-(void)enumerateEntitiesAndRelationshipsUsingBlock:(/*^block*/id)arg1 ;
@end

