/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:41:12 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/PDFKit.framework/PDFKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <PDFKit/PDFKit-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class PDFFormFieldPrivateVars;

@interface PDFFormField : NSObject <NSCopying> {

	PDFFormFieldPrivateVars* _private;

}
-(void)dealloc;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)stringValue;
-(void)setStringValue:(id)arg1 ;
-(void)commonInit;
-(long long)buttonType;
-(void)setDocument:(id)arg1 ;
-(id)document;
-(id)fieldName;
-(void)setFieldName:(id)arg1 ;
-(CFDictionaryRef)dictionaryRef;
-(CFDictionaryRef)createDictionaryRef;
-(void)addFieldTypeToDictionaryRef:(CFDictionaryRef)arg1 ;
-(id)initWithAnnotation:(id)arg1 ;
-(void)addFieldNameToDictionaryRef:(CFDictionaryRef)arg1 ;
-(id)initWithFormDictionary:(CGPDFDictionaryRef)arg1 ;
-(id)defaultStringValue;
-(void)clearDictionaryRef;
-(int)fieldType;
-(BOOL)writeDefaultValue;
-(void)setFieldType:(int)arg1 ;
-(void)setButtonType:(long long)arg1 ;
-(void)setDefaultStringValue:(id)arg1 ;
-(void)setWriteDefaultValue:(BOOL)arg1 ;
-(void)addNameValueToDictionaryRef:(CFDictionaryRef)arg1 ;
-(void)addStringValueToDictionaryRef:(CFDictionaryRef)arg1 ;
-(void)addNameDefaultValueToDictionaryRef:(CFDictionaryRef)arg1 ;
-(void)addStringDefaultValueToDictionaryRef:(CFDictionaryRef)arg1 ;
-(void)commonCreateDictionaryRef:(CFDictionaryRef)arg1 ;
@end

