/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:38:54 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/CoreData.framework/CoreData
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSSQLFetchRequestContext.h>

@interface NSSQLXPCFetchRequestContext : NSSQLFetchRequestContext
-(BOOL)executeRequestCore:(id*)arg1 ;
-(void)executeEpilogue;
@end

