/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:53:24 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsUI2/NewsUI2-Structs.h>
#import <UIKitCore/UIView.h>

@interface NewsUI2.HeadlineViewTextView : UIView {

	 titleLabel;
	 excerptLabel;
	 publisherImageView;
	 publisherLabel;

}
-(id)initWithCoder:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
@end

