/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:53:24 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface NUPaywallEventData : NSObject {

	 viewData;
	 articleData;
	 channel;
	 feedData;
	 groupData;
	 referral;
	 qToken;

}
-(id)init;
-(id)initWithPaywallViewData:(id)arg1 headline:(id)arg2 channel:(id)arg3 feed:(id)arg4 paywallGroupData:(id)arg5 referral:(id)arg6 qToken:(id)arg7 ;
@end

