/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:53:13 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/LocalAuthentication.framework/Support/DaemonUtils.framework/DaemonUtils
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
#import <DaemonUtils/DaemonUtils-Structs.h>
@class NSObject;

@interface DaemonUtils : NSObject {

	NSObject*<OS_dispatch_queue> _serverQueue;

}

@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> serverQueue;              //@synthesize serverQueue=_serverQueue - In the implementation block
+(id)sharedInstance;
+(id)callerDisplayNameWithPid:(int)arg1 auditToken:(SCD_Struct_Ca0)arg2 bundleId:(id*)arg3 ;
+(void)dispatchReallyAfter:(long long)arg1 tolerance:(double)arg2 queue:(id)arg3 block:(/*^block*/id)arg4 ;
+(id)_uuidForPid:(int)arg1 ;
+(id)_pluginDisplayNameForUUID:(id)arg1 bundleId:(id*)arg2 ;
+(id)_callerUUID;
+(id)_pluginDisplayNameForPID:(int)arg1 bundleId:(id*)arg2 ;
+(BOOL)_isSiriExtensionOf:(id)arg1 runningWithAuditToken:(SCD_Struct_Ca0)arg2 ;
+(BOOL)deviceHasSEP;
+(BOOL)deviceHasPearl;
-(id)init;
-(NSObject*<OS_dispatch_queue>)serverQueue;
@end

