/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:57:40 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <VideosUI/VUIDocumentContextData.h>

@class NSString;

@interface VUIDocumentContextDataMovie : VUIDocumentContextData {

	NSString* _movieID;

}

@property (nonatomic,copy,readonly) NSString * movieID;              //@synthesize movieID=_movieID - In the implementation block
-(id)jsonData;
-(id)initWithMovieID:(id)arg1 ;
-(NSString *)movieID;
@end

