/*
* This header is generated by classdump-dyld 1.0
* on Saturday, June 6, 2020 at 11:44:54 PM US Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /System/Library/Frameworks/QuickLook.framework/QuickLook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/QLPreviewItemProvider.h>

@class NSArray;

@interface QLDataSource : NSObject <QLPreviewItemProvider> {

	NSArray* _previewItems;

}
-(id)initWithPreviewItems:(id)arg1 ;
-(void)previewItemAtIndex:(unsigned long long)arg1 withCompletionHandler:(/*^block*/id)arg2 ;
@end

